version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: sc.collection.json
          environment: sc.env.json
          
scheduled-workflows:
  version: 2
  commit:
    jobs:
      - build

  triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "* * * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - master

# triggers: 
#  - schedule: commment
#     cron: "*/1 * * * *"
#     filters: 
#       branches: 
#         only: 
#           - main
