version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: sc.collection.json
          environment: sc.env.json                
scheduled-workflows:
  version: 2
  commit:
    jobs:
      - test
      - deploy
  hourly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - coverage  
      
       
# workflows:
#   version: 2
#   commit:
#     jobs:
#       - build
#   triggers:
#       - schedule:
#           cron: "* * * * *" 
#           filters:
#             branches:
#               only:
#                 - master

# triggers: 
#  - schedule: commment
#     cron: "*/1 * * * *"
#     filters: 
#       branches: 
#         only: 
#           - main
